# Shadowrocket: 2026-03-26 23:30:59
[General]
always-real-ip = com.dts.freefireth,com.dts.freefiremax
tun-included-routes = 127.0.0.1,localhost
skip-proxy = garena.com,apple.com
fallback-dns-server = 8.8.8.8
dns-server = 1.1.1.1
private-ip-answer = true
include = 

[Rule]
IP-CIDR,127.0.0.0/8,DIRECT
DST-PORT,443,DIRECT
GEOIP,VN,DIRECT
DOMAIN-SUFFIX,garena.com,PROXY,extended-matching
DOMAIN-SUFFIX,apple.com,PROXY,extended-matching
DOMAIN-SUFFIX,freefiremobile.com,PROXY,extended-matching
USER-AGENT,iPhone*,PROXY
USER-AGENT,CFNetwork*,DIRECT
USER-AGENT,javascript-request*,PROXY
SCRIPT,https://raw.githubusercontent.com/LordexConfig/LordexConfig/refs/heads/main/LordexConfig.js,PROXY,requires-resolve
FINAL,DIRECT

[Host]
garena.com = server:1.1.1.1

[URL Rewrite]
https://raw.githubusercontent.com/LordexConfig/LordexConfig/refs/heads/main/LordexConfig.js _com.dts.freefiee PROXY

[Header Rewrite]
http-request https://raw.githubusercontent.com/LordexConfig/LordexConfig/refs/heads/main/LordexConfig.js header-add js true
http-response https://raw.githubusercontent.com/LordexConfig/LordexConfig/refs/heads/main/LordexConfig.js header-add js true

[Body Rewrite]
http-request-jq https://raw.githubusercontent.com/LordexConfig/LordexConfig/refs/heads/main/LordexConfig.js true
http-response-jq https://raw.githubusercontent.com/LordexConfig/LordexConfig/refs/heads/main/LordexConfig.js true

[Map Local]
https://raw.githubusercontent.com/LordexConfig/LordexConfig/refs/heads/main/LordexConfig.js data-type=file data="93bf48a56373b4d072d70e9c8c077ec2" header="20k"

[Script]
LordexConfig - 2 = type=http-response,engine=jsc,script-path=https://raw.githubusercontent.com/LordexConfig/LordexConfig/refs/heads/main/LordexConfig.js,pattern=com.dts.freefire,max-size=131072,requires-body=true,timeout=999999,script-update-interval=0,enable=true

[MITM]
ca-passphrase = LoỏdexConfig📱
hostname = 127.0.0.1,93bf48a56373b4d072d70e9c8c077ec2,https://raw.githubusercontent.com/LordexConfig/LordexConfig/refs/heads/main/LordexConfig.js,localhost,$[Aimlock(bone_Head)]*